interfaces:
    - name: xe-0/0/1
      description: "connect l2-srv1"
      vlan_id: 1
    - name: xe-0/0/2
      description: "connect l2-srv2"
      vlan_id: 1

inet_interfaces:
    - name: xe-0/0/0
      ip: 10.0.1.2/30
      description: "connect 2 vqfx1"
    - name: irb
      description: "vRouter Gateway for l2 srvs"
      ip: 172.16.3.1/24
    - name: lo0
      description: "vqfx Loopback"
      ip: 2.2.2.3/32

router_id: 2.2.2.3
overlay_asn: 64512
local_as: 64502
local_address: 2.2.2.3

peers:
    - name: spine1
      neighbor: 10.0.0.1
      peer_as: 64601
