interfaces:
    - name: xe-0/0/1
      description: "connect l-srv1"
      vlan_id: 1
    - name: xe-0/0/2
      description: "connect l-srv2"
      vlan_id: 1

inet_interfaces:
    - name: xe-0/0/0
      ip: 10.0.0.2/30
      description: "connect 2 vqfx1"
    - name: irb
      description: "vRouter Gateway for all srvs"
      ip: 172.16.2.1/24
    - name: lo0
      description: "vqfx Loopback"
      ip: 2.2.2.2/32   

router_id: 2.2.2.2
overlay_asn: 64512
local_as: 64501
peer_as: 64601
neighbor: 10.0.0.1
local_address: 2.2.2.2
